services:
  mysql:
    image: arm64v8/mysql:9.0.1
    container_name: mysql_container
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "" # Blank password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "shopapp_online"
    restart: always
    networks:
      - shopapp-online
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    depends_on:
      - mysql
    ports:
      - "90:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M
    networks:
      - shopapp-online

networks:
  shopapp-online:
    name: shopapp-online
    driver: bridge
